version: "3.8"
services:
  app:
    container_name: survey-monkey-test
    image: survey-monkey-test
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000


