apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey
  namespace: survey
spec:
  selector:
    matchLabels:
      app: survey
  template:
    metadata:
      labels:
        app: survey
    spec:
      containers:
      - name: survey
        image: reechee/survey-monkey-test:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
