apiVersion: v1
kind: Service
metadata:
  name: survey
  namespace: survey
  labels:
    app: survey
spec:
  type: LoadBalancer
  selector:
    app: survey
  ports:
  - port: 3000
    name: survey
    targetPort: 3000
